[package]
name = "sci"
version = "2.2.3"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
log = "0.4"
sys-mount = "2.0.2"
system_shutdown = "4.0.1"
shell-words = "1.1.0"
vsock = "0.3.0"
