[package]
name = "oci-register"
version = "0.0.1"
authors = ["Marcus Sch√§fer <marcus.schaefer@elektrobit.com>"]
edition = "2018"

[dependencies]
clap = { version = "3.0.14", features = ["derive"] }
claim = { version = "0.3.1" }
